centrifuge/tinlake

src/pile.sol
src/test/pile.t.sol

fix: pile drip

---

src/pile.sol
src/test/pile.t.sol

please finish review of #19 first
- burden method returns the current debt of a loan without changing the state

feat: pile burden method

---

src/admin.sol
src/admit.sol
src/appraiser.sol
src/shelf.sol
src/test/admin.t.sol
src/test/admit.t.sol
src/test/mock/admit.sol
src/test/mock/appraiser.sol
src/test/mock/pile.sol
src/test/mock/shelf.sol
src/test/mock/title.sol

- admin contract with whitelist method
admin deployment and integration test will follow in the next PR

feat: admin contract

---

src/pile.sol
src/reception.sol
src/test/integration/system.t.sol
src/test/mock/shelf.sol
src/test/reception.t.sol

msg.sender is used for repay and closing of a loan.

fix: removed usrT parameter from repay

---

bin/admin

every admin needs to be added to the pile contract for setting the `fee`.

feat: admin script calls pile rely

---

src/pile.sol

- added incDebt and decDebt
- removed collect from borrow
- added init loan method

feat: pile improvements

---

src/shelf.sol
src/test/admit.t.sol
src/test/integration/system.t.sol
src/test/mock/shelf.sol

Track initial principal

---

src/actions/test/actions.t.sol
src/core/test/mock/pile.sol

tests are currently broken resulted by a auto-merge conflict

fix: pile mock test

---

src/core/lender/deployer.sol
src/core/test/system/test_utils.sol

- currency in constructor
- guarantees correct currency is used 
- added additional requires to guarantee correct order

feat: added senior deployment to lender deployer

---

src/core/borrower/deployer.sol

- ensures the correct order of deploy calls

chore: added requires to borrower deployer

---

src/core/borrower/collect/collector.sol
src/core/borrower/collect/test/collector.t.sol

- added require for check
- added test
- changed to more descriptive naming

fix: collector requires nftPrice > 0

---

src/core/lender/deployer.sol
src/core/test/system/borrower/balance.t.sol
src/core/test/system/borrower/borrow.t.sol
src/core/test/system/borrower/close.t.sol
src/core/test/system/borrower/issue.t.sol
src/core/test/system/borrower/lock.sol
src/core/test/system/interfaces.sol
src/core/test/system/lender/redeem.t.sol
src/core/test/system/lender/supply.t.sol
src/core/test/system/setup.sol
src/core/test/system/system.sol
src/core/test/system/system.t.sol
src/core/test/system/users/investor.sol

* creates BaseDistributorFab
* whitelistinvestor -> investor, move to users
* updates tests for pre/post conditions
* optimises lender deploy config/setup

feat: added pre/post conditions for lender system tests, unhappy cases, new lender config setup

---

src/core/lender/assessor.sol
src/core/lender/test/assessor.t.sol
src/core/lender/tranche/operator/base.sol

methods added to assessor
- added supplyApprove
- needed by operator
- calcMaxSeniorAssetValue
- needed for supplyApprove
- currentJuniorRatio
- needed by external contracts
added tests for all methods

feat: assessor added supplyApprove & redeemApprove

---

src/core/borrower/ceiling/creditline.sol
src/core/borrower/ceiling/principal.sol
src/core/borrower/pile.sol
src/core/borrower/shelf.sol
src/core/borrower/test/creditline.t.sol
src/core/borrower/test/pile.t.sol
src/core/borrower/test/principal.t.sol
src/core/lender/assessor.sol
src/core/lender/distributor/base.sol
src/core/lender/distributor/switchable.sol
src/core/lender/tranche/senior_tranche.sol
src/core/test/simple/token.sol
src/core/test/system/borrower/balance.t.sol
src/core/test/system/borrower/borrow.t.sol

zero warnings after this PR is in 💪

fix: use  new safeMath naming

---

src/core/test/system/base_system.sol
src/core/test/system/borrower/close.t.sol
src/core/test/system/borrower/issue.t.sol
src/core/test/system/borrower/lock.sol
src/core/test/system/borrower/principal_ceiling/borrow.t.sol
src/core/test/system/borrower/principal_ceiling/repay.t.sol
src/core/test/system/borrower/switchable_distributor/balance.sol
src/core/test/system/borrower/switchable_distributor/withdraw.t.sol
src/core/test/system/borrower/unlock.t.sol
src/core/test/system/lender/assessor_full_invest/supply_two_tranche.sol
src/core/test/system/lender/base/redeem_single_tranche.t.sol
src/core/test/system/lender/base/redeem_two_tranche.sol
src/core/test/system/lender/base/supply_single_tranche.t.sol
src/core/test/system/lender/base/supply_two_tranche.sol
src/core/test/system/lender/switchable/supply_single_tranche.t.sol
src/core/test/system/system.t.sol

- also optimisations for creating TestUsers

chore: simpleSupply and simpleFail, two tranches with base distributor and default assessor

---

src/borrower/ceiling/creditline.sol
src/borrower/deployer.sol
src/borrower/test/deployer.t.sol
src/lender/deployer.sol
src/test/system/base_system.sol
src/test/system/borrower/borrow/creditline_borrow.t.sol
src/test/system/borrower/borrow/principal_borrow.t.sol
src/test/system/borrower/repay/creditline_repay.t.sol
src/test/system/borrower/repay/principal_repay.t.sol
src/test/system/interfaces.sol
src/test/system/lender/assessor/default_interest.t.sol
src/test/system/lender/assessor/full_investment_interest.t.sol
src/test/system/lender/base/redeem_single_tranche.t.sol
src/test/system/lender/base/supply_single_tranche.t.sol
src/test/system/lender/base/supply_two_tranche.t.sol
src/test/system/lender/distributor/default.t.sol
src/test/system/scenarios.t.sol
src/test/system/setup.sol

- refactor: ceiling method: creditLine. Debt can grow bigger then credit Line when interest accrues. In this case credit line should return 0.
- added tests from credit line
- added creditline stup to deployer

add: tests for creditline contract

---

bin/test/setup_local_config.sh
src/borrower/test/pile.t.sol
src/lender/tranche/operator/allowance.sol
src/root.sol
src/test/system/borrower/borrow/principal_borrow.t.sol
src/test/system/lender/supply_redeem/redeem_single_tranche.t.sol
src/test/system/lender/supply_redeem/supply_single_tranche.t.sol
src/test/system/scenarios.t.sol

- adjust paths in deploy scripts
- use safeMath in operator and tests
- make allowance maps public
- remove dupl. depend call

fix - use safe math

---

bin/util/util.sh

deploy script was broken if the condition was true.

fix: build script correct dapp build path

---

src/borrower/pile.sol
src/borrower/shelf.sol
src/borrower/test/mock/nft.sol

fixes issue B and issue E from audit report

fix: pile now check (issue B) && shelf ownerOf view (issue E)

---

src/borrower/ceiling/creditline.sol
src/borrower/ceiling/principal.sol
src/borrower/collect/collector.sol
src/borrower/collect/test/collector.t.sol
src/borrower/pile.sol
src/borrower/shelf.sol
src/borrower/test/creditline.t.sol
src/borrower/test/pile.t.sol
src/borrower/test/principal.t.sol
src/borrower/test/shelf.t.sol
src/test/system/interfaces.sol
src/test/system/scenarios.t.sol
src/test/system/users/admin.sol

implements suggestion 3 from the report.
**NOTE**
Breaking Changes for `tinlake.js`

chore: consistent file usage 

---

bin/lender/deploy.sh
bin/util/util.sh
src/lender/deployer.sol
src/test/system/setup.sol

- rm constructor parameter in senior fabs
- added initSenior method
- call optional only if senior tranche should be deployed
- adjusted bash script

chore: lenderDeployer rm params from constructor & added token names

---

bin/util/util.sh
src/borrower/test/pile.t.sol

- added test for changeRate if the debt == 0

test: added test for change rate edge case

---

bin/util/util.sh
src/lender/deployer.sol
src/lender/tranche/operator/proportional.sol
src/lender/tranche/test/investor.t.sol
src/lender/tranche/test/operator.t.sol
src/lender/tranche/test/proportional_operator.t.sol
src/test/system/base_system.sol
src/test/system/borrower/repay/creditline_repay.t.sol
src/test/system/lender/operator/allowance.t.sol
src/test/system/lender/operator/proportional.t.sol
src/test/system/setup.sol

- impl of prop operator
- tests for prop operator
**spec for prop operator** 
https://centrifuge.hackmd.io/iP40MNA2TlaYF5F_TeyzRQ
**modelling for prop operator** 
https://docs.google.com/spreadsheets/d/1u-3qjHJJthc87qGUMhxgr1ro75IMxQFhEU21RpJq_Vw/edit#gid=1024434668

feat: prop operator

---

src/lender/tranche/operator/proportional.sol

the calcRedeemCurrencyAmount needs to be internal instead of public

fix: prop operator calcRedeemCurrencyAmount method internal

---

src/borrower/deployer.sol
src/borrower/fabs/collector.sol
src/borrower/fabs/creditline.sol
src/borrower/fabs/nftfeed.sol
src/borrower/fabs/pile.sol
src/borrower/fabs/pricepool.sol
src/borrower/fabs/principal.sol
src/borrower/fabs/shelf.sol
src/borrower/fabs/threshold.sol
src/borrower/fabs/title.sol

fixes: create2 redeployment bug

chore: own fab files for borrower

---

src/lender/deployer.sol
src/lender/fabs/allowance_operator.sol
src/lender/fabs/default_assessor.sol
src/lender/fabs/default_distributor.sol
src/lender/fabs/full_investment_assessor.sol
src/lender/fabs/proportional_operator.sol
src/lender/fabs/senior_tranche.sol
src/lender/fabs/tranche.sol
src/lender/fabs/whitelist_operator.sol

chore: added own files for lender fabs

---

package-lock.json
src/lender/test/mock/reserve.sol
src/lender/tranche/test/v3_tranche.t.sol
src/lender/tranche/tranche.sol
src/lender/tranche/v3/ticker.sol
src/lender/tranche/v3/tranche.sol

to be done:
- more tests covering edge cases 
- add investor auth to supplyOrder & redeemOrder & disburse to support investor memberlist

feature - v3 tranche contract

---

src/lender/coordinator.sol
src/lender/test/coordinator.t.sol
src/lender/test/mock/epoch-tranche.sol
src/lender/test/mock/reserve.sol
src/lender/ticker.sol

- epoch coordinator body with interfaces
- tranche mock contract
- reserve mock contract

feat: epoch coordinator contract body and mocks

---

src/borrower/pile.sol
src/borrower/test/pile.t.sol

- add fixedRate var to rate groups
- adjust file function to set fixedRates on rate groups. If no fixedRate is set for a group value => 0
- in incDebt Add fixedBorrowFee: `currencyAmount = currencyAmount + currencyAmount*fixedRate` If fixedRate is zero, no fixedBorrowFee is added to currencyAmount
- Accrue interest on the fixedBorrowFee together with borrowAmount

feature: pile support fixed rates

---

src/lender/test/assessor.t.sol

fix: tranche mock includes for tests

---

src/borrower/feed/navfeed.sol
src/borrower/feed/nftfeed.sol
src/borrower/test/mock/pile.sol
src/borrower/test/navfeed.t.sol
src/lender/assessor.sol
src/lender/coordinator.sol
src/lender/test/coordinator-base.t.sol
src/test/system/base_system.sol
src/test/system/borrower/unlock.t.sol
src/test/system/lender/invest.t.sol
src/test/system/lender/lender_scenarios.t.sol
src/test/system/scenarios.t.sol
src/test/system/setup.sol
src/test/system/users/admin.sol

- fix interest rate bug in NAV
- system tests with lender focus

fix: NAV interest rate bug & system tests

---

src/borrower/feed/test/navfeed.t.sol
src/borrower/feed/test/nftfeed.t.sol
src/lender/assessor.sol
src/lender/coordinator.sol
src/lender/test/assessor.t.sol
src/lender/test/mock/assessor.sol
src/lender/test/mock/tranche.sol

- wrote more unit tests for assessor
- changes in methods
- changeSeniorAsset
- borrowUpdate
- repaymentUpdate
- calcTokenPrice

chore: assessor funcs & tests

---

src/borrower/deployer.sol
src/borrower/feed/navfeed.sol
src/borrower/feed/test/navfeed.t.sol
src/borrower/test/deployer.t.sol
src/test/system/setup.sol

it is no longer being used in navfeed.sol

fix: rm maxFeedDays

---

src/borrower/feed/buckets.sol
src/borrower/feed/test/buckets.t.sol
src/test/system/lender/lender_scenarios.t.sol
src/test/system/users/investor.sol

- the remove bucket function didn't cover some edge cases
- re-wrote the function and added additional unit tests for buckets

fix: removeBuckets in NAVFeed & lender system test

---

src/lender/test/tranche.t.sol
src/lender/tranche.sol

The problem occurs if not all epochs are disbursed in one run by using the endEpoch parameter.
The disburse starts with `orderedInEpoch` and the method would disburse all including endEpoch.
Afterwards orderedInEpoch is set to endEpoch. Which was wrong because the next disburse would start with previous last disburse epoch.
**Correct Behaviour**
`orderedInEpoch` should be updated with `endEpoch + 1`.

fix: end epoch bug in tranche

---

src/borrower/feed/navfeed.sol
src/lender/tranche.sol

- more comments in NAV feed and tranche
**Current Impl**
A user can place an order if one of the following is true
- `users[usr].orderedInEpoch == 0`
- `users[usr].orderedInEpoch  == currentEpoch`
**New Impl**
A user can place an order if one of the following is true
-  `(users[usr].supplyCurrencyAmount == 0 && users[usr].redeemTokenAmount == 0)`
-  `users[usr].orderedInEpoch  == currentEpoch`
Currently we never set orderedInEpoch back to 0. If a user supply/redeem and disburse and want to re-supply after a couple of epochs. We currently would require to call disburse once to set orderedInEpoch back to currentEpoch. Before an order can be placed. Which is counter intuitive because an order was not placed.
We could add a check in disburse if remaining supply and redeem are empty to set …

chore: order allowed checks for supplyOrder and redeemOrder

---

src/borrower/feed/navfeed.sol
src/borrower/feed/nftfeed.sol
src/borrower/feed/test/buckets.t.sol
src/borrower/feed/test/navfeed.t.sol
src/lender/assessor.sol
src/lender/coordinator.sol
src/lender/fabs/memberlist.sol
src/lender/test/assessor.t.sol
src/lender/test/coordinator-base.t.sol
src/lender/test/coordinator-closeEpoch.t.sol
src/lender/test/memberlist.t.sol
src/lender/test/mock/assessor.sol
src/lender/test/mock/navFeed.sol
src/lender/test/mock/reserve.sol
src/lender/test/mock/tranche.sol
src/lender/test/operator.t.sol
src/lender/test/tranche.t.sol
src/lender/token/memberlist.sol
src/lender/tranche.sol
src/test/system/base_system.sol
src/test/system/borrower/borrow/principal_borrow.t.sol
src/test/system/borrower/repay/principal_repay.t.sol
src/test/system/borrower/unlock.t.sol
src/test/system/lender/lender_scenarios.t.sol
src/test/system/scenarios.t.sol
src/test/system/setup.sol

removed all warnings except pragma experimental and one other.

chore: fix compiler warnings

---

src/fixed_point.sol
src/lender/assessor.sol
src/lender/coordinator.sol
src/lender/test/coordinator-validate.t.sol
src/test/system/lender/integration.t.sol
src/test/system/lender/lender_scenarios.t.sol

- Introducing a new pool closing flag in the coordinator which will be activated in the closeEpoch function if the junior tranche lost all its value
- changes the behaviour of the validate function (ignores poolConstraints only allows redeem not supply)
- added unit tests
- added system test

feat: pool closing flag in coordinator

---

.gitmodules
src/borrower/test/deployer.t.sol
src/lender/test/reserve.t.sol
src/lender/test/tranche.t.sol
src/test/system/setup.sol

fix: update tinlake-erc20 for dapp remappings

---

src/lender/adapters/mkr/clerk.sol
src/lender/adapters/mkr/test/clerk.t.sol
src/lender/adapters/mkr/test/mock/mgr.sol

clerk: fix juniorStake function
clerk: add function to change mgr ownership
clerk: add function to transfer surplus DAI back to reserve
clerk: add more liquidation conditions: hard liquidation & global settlement
update ds-test submodule

add: withdraw & ownerSwap functions to clerk

---

src/test/system/base_system.sol
src/test/system/borrower/borrow/principal_borrow.t.sol
src/test/system/borrower/repay/principal_repay.t.sol
src/test/system/borrower/unlock.t.sol
src/test/system/borrower/withdraw.t.sol
src/test/system/collector/collect.t.sol
src/test/system/lender/mkr/mkr_basic.t.sol
src/test/system/lender/mkr/mkr_scenarios.t.sol
src/test/system/test_suite.sol

- mkr test for multiple draw 
- clean up test framework

tests: mkr test for multiple draw 

---

README.md
src/lender/admin/member.sol
src/lender/test/memberAdmin.t.sol
src/lender/test/mock/memberlist.sol

- Add member admin contract.
- Update readme with test instructions and general wording changes.

feat: add member admin contract, update readme

---

src/lender/tranche.sol

- the tranche deposit method returns the payout amount in tokens and in currency
- in the potential case that the reserve is missing some WEI because of rounding errors, we wouldn't fail  instead we return the token amount or currency which is available
- they returned `payoutCurrencyAmount, payoutTokenAmount` values should return the amounts which have been transferred

fix: tranche correct payout amounts

---

src/lender/adapters/mkr/clerk.sol
src/lender/adapters/mkr/test/clerk.t.sol
src/lender/adapters/mkr/test/mock/gemJoin.sol
src/lender/adapters/mkr/test/mock/mgr.sol
src/lender/adapters/mkr/test/mock/urn.sol
src/test/simple/mkr.sol

**MIP21 mgr Changes**
- ilk variable removed from mgr
- collateral in Maker is the RWA token not DROP
- mgr owner changed to file method
- cdptab  based on urn and not mgr
- cdpink change to drop balance of mgr

refactor: adjust clerk to mgr MIP21 version

---

src/lender/adapters/mkr/clerk.sol
src/lender/adapters/mkr/test/clerk.t.sol
src/lender/adapters/mkr/test/mock/jug.sol
src/lender/adapters/mkr/test/mock/vat.sol
src/test/simple/mkr.sol
src/test/system/lender/mkr/mkr_scenarios.t.sol

**Content**
- removed cdptab function from clerk
- clerk debt function is view and guarantees up to date maker debt

chore: clerk.debt() changed to view

---

src/borrower/feed/navfeed.sol

- added currentPresentValue method for optimisation

feat: NAV-v2 currentPresentValue method 

---

README.md
src/borrower/feed/navfeed.sol
src/borrower/shelf.sol
src/borrower/test/mock/shelf.sol
src/borrower/test/mock/title.sol

- re ordering of file methods at the beginning
- reCalcNAV method and reCalcTotalDiscount

feat: nav-v2 reCalcNAV method

---

src/borrower/feed/creditline.sol
src/borrower/feed/navfeed.sol
src/borrower/feed/principal.sol
src/borrower/feed/test/navfeed.t.sol
src/borrower/feed/test/nftfeed.t.sol

please review #590 first
- replaced mappings with uint128 structs
- added safe cast method

feat: nav-v2 with uint128 and structs

---

src/borrower/feed/navfeed.sol
src/borrower/shelf.sol
src/lender/coordinator.sol
src/test/system/lender/lender_scenarios.t.sol

- added zeroPV for unlock
- fixed rounding system test case
- closeEpoch returns boolean

feat: nav-v2 zeroPV for unlock

---

src/borrower/feed/navfeed.sol
src/borrower/feed/test/navfeed.t.sol

- rm internal borrow method
- only reCalcNAV if necessary 
- fmt

chore: nav-v2 rm internal borrow method

---

.github/workflows/push-to-main.yml
foundry.toml

Changed Github Action to new `main` branch instead of `develop`.

chore: github action for main branch
