- bin/deploy-mocks
sub-folder in `out` are removed in latest dapp version
> fix: mock nft and currency deploy script

- src/pile.sol
- src/test/pile.t.sol
fixes the global `Debt` variable update. 
After a loan has been repaid the `fees[fee].debt` hasn't been updated.
The global `Debt` updated happens based on `fees[fee].debt` and caused the problem.
> fix: fee debt update after repay

- src/reception.sol
- src/test/reception.t.sol
the idea to have a byte32 field for the version in place.
In the future, it might be a hash to receive additional information about the Tinlake deployment from IPFS.
For now we are using it in the UI to support different contract versions.
> feat: added version to reception contract

- src/admin.sol
- src/admit.sol
- src/deployer.sol
- src/desk.sol
- src/pile.sol
- src/reception.sol
- src/shelf.sol
- src/test/desk.t.sol
- src/valve.sol
Closes #72 and #60 .
Sets up a `file` method for external configurations, and introduces `depend` for core contract dependencies.
> File and depend methods

- src/pile.sol
- src/shelf.sol
- src/test/integration/system.t.sol
- src/test/pile.t.sol
I realized we don't need to store an extra chi for each loan. 
Instead of storing the `debt` and `chi` for each loan, we could adapt the completely the maker `pot` pattern and only store one variable for both called `pie`. (I called it `pie` for now to understand the similarity to maker `pot`).
I could remove the `update` method as well.
We might adjust `balance` and the Debt stored in fees map to the pie format to be consistent.
In the upcoming tickets, we will move the interest calculation to an own module.
> feat: removed loan chi from pile

- src/core/lender/assessor/base.sol
- src/core/lender/assessor/test/base.t.sol
I think it was wrong because we refactored the ratio methods.
The method is called in the redeemApprove for junior
```javascript
if (tranche == junior && safeSub(calcAssetValue(junior), currencyAmount) >= calcMinJuniorAssetValue()) {
return true;	 
}
```
Let's imagine we close the pool. Senior redeemed all the currency. 
For junior it would not be possible to redeem now
> fix: assessor calcMinJuniorAssetValue

- bin/util/util.sh
- src/lender/assessor/base.sol
- src/lender/assessor/test/base.t.sol
- the method didn't prevent zero division in case the junior asset value == 0
> fix: currentJuniorRatio method in assessor zero cases

- src/borrower/pile.sol
the `total` debt is not stored in pie format.
Instead, it is increased every time with the delta of a fee group interest update.
See: `safeSub(rmul(updatedChi, pie), rmul(chi, pie)`
Over time and with the different fee groups we noticed small rounding errors (max: `2 wei`)
It results in revert in the last loan repayment in the decDebt method because 
`currencyAmount > total`
> fix: last total debt decrease

- src/borrower/feed/navfeed.sol
- src/borrower/feed/nftfeed.sol
- src/borrower/feed/test/nftfeed.t.sol
- src/borrower/test/deployer.t.sol
- added file method to NFT Feed for score cards
- no scorecard by default in NFT Feed
- added file method to NFT Feed for score card with additional recoveryRatePD
- default score card for testing is only initialised in NAV Feed init method
> chore: file methods for scorecards in NFTFeed and NAVFeed

- src/lender/test/tranche.t.sol
- src/lender/tranche.sol
- if the tranche doesn't have enough currency or token instead of failing  the user should receive the maximum possible amount
- calcDisburse should always round off instead of round up instead of depending if the last value is `> 5` or `< 5`
> fix: safeTransfer for tranche & calcDisburse rounding off

- src/lender/test/tranche.t.sol
- src/lender/tranche.sol
- recovery transfer allows governance to intervene if tokens get stuck in the tranche contract
- long term method should be removed but for the first deployments it is an additional security mechanism to avoid locked funds
> feat: recovery transfer for tranche

- src/lender/coordinator.sol
- src/lender/test/coordinator-submitEpoch.sol
**Summary**
- it should be possible to submit the current state (submission with only zeros) to start the challenge period
- in some cases it is not possible to submit a solution which is improving the current state
- Example: maxReserve violated and only supply orders and no redeem orders (the only solution is a zero submission)
- it should be allowed to submit a zero submission to start the challenge period
- fix typo in weights name
**Details**
In an improvement scenario we calculate the improvement score of the current state. The improvement score of the current state is used as benchmark for the submitted solution. A current state submission should be accepted as an improvement.
> fix: improvementScore condition in coordinator

- src/borrower/feed/test/navfeed.t.sol
- src/lender/assessor.sol
- src/lender/coordinator.sol
- src/lender/definitions.sol
- src/lender/fabs/assessoradmin.sol
- src/lender/test/assessor.t.sol
- src/lender/test/coordinator-base.t.sol
- src/lender/test/coordinator-closeEpoch.t.sol
- src/lender/test/coordinator-executeEpoch.t.sol
- src/lender/test/coordinator-improvementScore.t.sol
- src/lender/test/coordinator-submitEpoch.sol
- src/lender/test/definitions.t.sol
- src/lender/test/mock/assessor.sol
- src/lender/test/mock/clerk.sol
- src/test/system/base_system.sol
- src/test/system/lender/lender_scenarios.t.sol
**Summary**
In preparation for the MKR adapter I refactored the coordinator and assessor to make the integration more smoothly.
**Details**
- moved all pure functions from the coordinator and assessor to a own contract (definitions)
- assessor uses inheritance with the definition contract
- added a pure validate function to coordinator
- fix reBalancingBug not lose track of expectedSeniorAsset value
- added ratio < ONE check to reBalanceMethod
- changeSeniorAsset in assessor doesn't require a ratio anymore
- the ratio is calculated based on the recent nav and reserve
- fixed some existing compiler warnings
> feat: definitions contract & assessor.changeSeniorAsset

- src/lender/adapters/mkr/clerk.sol
- src/lender/reserve.sol
- src/lender/test/mock/clerk.sol
- src/lender/test/mock/reserve.sol
- src/lender/test/reserve.t.sol
The currency in the reserve is automatically used to repay/reduce lender adapter debt. The deposit method automatically calls clerk.wipe. If currency is requested the reserve uses the adapter to request additional currency.(clerk.draw)
**Reserve Contract**
- lending adapter can be optional set in the reserve contract 
-
**Clerk Contract**
- changed reserve call to hardDeposit and hardPayout
- otherwise we would have the following problem
- tranche contract calls payout
- additional currency is required and clerk.draw call happens
- draw calls internally deposit
- deposit would use the receive currency to repay adapter debt
- the just received currency from adapter would be immediately used to repay back to the adapter
> feat: integrated lending adapter into reserve

- src/fixed_point.sol
- src/lender/adapters/mkr/assessor.sol
- src/lender/adapters/mkr/clerk.sol
- src/lender/adapters/mkr/deployer.sol
- src/lender/adapters/mkr/test/assessor.t.sol
- src/lender/adapters/mkr/test/clerk.t.sol
- src/lender/adapters/mkr/test/mock/mgr.sol
- src/lender/adapters/mkr/test/mock/spotter.sol
- src/lender/adapters/mkr/test/mock/vat.sol
- src/lender/assessor.sol
- src/lender/coordinator.sol
- src/lender/reserve.sol
- src/lender/test/assessor.t.sol
- src/lender/test/coordinator-closeEpoch.t.sol
- src/lender/test/coordinator-executeEpoch.t.sol
- src/lender/test/mock/assessor.sol
- src/lender/test/mock/clerk.sol
- src/lender/test/mock/coordinator.sol
- src/lender/test/mock/reserve.sol
- src/lender/test/reserve.t.sol
- src/test/simple/mkr.sol
- src/test/system/assertions.sol
- src/test/system/lender/mkr/mkr_scenarios.t.sol
- src/test/system/setup.sol
- src/test/system/test_suite.sol
**New Total Balance Function in Assessor**
- over time the `clerk.remainingCredit` will decrease because of the accumulated debt interest, therefore a buffer is reduced from the  remainingCredit to prevent the usage of currency which is not available.
- the buffer variable uses the stability fee multiplied with time constant( which should be way greater than minimumEpochClose time)
**Tests**
- added integration test for on demand draw in reserve
> feat: added creditBuffer to totalBalance in assessor + drawOnDemand tests

- src/lender/coordinator.sol
- src/lender/test/coordinator-improvementScore.t.sol
**Summary**
- removed normalised distance for coordinator reserveImprovementScore
- the edge case of a zero maxReserve didn't allowed the normalization
- if the newReserve is bigger than the maxReserve the score is calculated in the following way
```
distance = newReserve-maxReserve; 
score = ONE/distance;
```
- the score will approximate zero for really high numbers
- tested up to `10^34` which should be enough for our use-case
> chore: new reserve improvement score implementation

- src/lender/coordinator.sol
- src/test/system/lender/lender_scenarios.t.sol
**Desc**
- if an epoch was closed without any orders the currencyAvailable was not updated
- the currency of repaid loans should be available for new borrows
> fix: reserve available update for a no orders epoch close

- src/lender/coordinator.sol
- src/lender/test/coordinator-base.t.sol
- src/lender/test/coordinator-closeEpoch.t.sol
We want to be able to automatically close epochs at 1 day intervals. This gives us 10 min buffer/leeway to do so.
> feat: update default min epoch time to 23 hours 50 mins

- src/lender/adapters/mkr/clerk.sol
- src/lender/adapters/mkr/test/clerk.t.sol
- src/lender/adapters/mkr/test/mock/jug.sol
- src/lender/reserve.sol
- src/test/simple/mkr.sol
- src/test/system/lender/mkr/mkr_scenarios.t.sol
**Content**
- `clerk.debt()` function should update the maker debt if not up to date
- all non view methods should use `debt()` instead of `cdptab()`
We should discuss if we want to add a `calcDebt()` function which calculates the debt for all `view` methods
**Pseudo Code for calcDebt()**
```javascript
function calcDebt() public view returns(uint) {
bytes32 ilk_ = ilk();
(, uint art) = vat.urns(ilk_, mgr.urn());
(, uint prev) = vat.ilks(ilk_);
(uint duty, uint rho) = jug.ilks(ilk_);
return rmul(art, rmul(rpow(safeAdd(jug.base(), duty), block.timestamp - rho, ONE), prev));
}
```
> fix: clerk.debt should drip mkr debt if needed

- src/lender/adapters/mkr/clerk.sol
- src/lender/adapters/mkr/test/clerk.t.sol
- src/lender/test/coordinator-executeEpoch.t.sol
- src/lender/test/mock/assessor.sol
**clerk added wipeThreshold**
- the debt is only repaid if amount is higher than the  wipe threshold
-  repaying a lower amount would cause more cost in gas fees than the debt reduction
**clerk  sink epochBorrowAmount**
- the sink amount can be higher than assessor. borrowAmountEpoch
- in that case  assessor. borrowAmountEpoch can be set to zero otherwise the safeSub would fail
> feat: clerk added wipeThreshold and fix sink borrowAmountEpoch

- src/borrower/feed/buckets.sol
- src/borrower/feed/navfeed.sol
- src/borrower/feed/test/buckets.t.sol
- instead of finding the first relevant bucket for the currentDiscount by increasing the current block.timestamp by a day
- a pointer keeps track of the `first bucket` in the future
- in the next call the this day might be already in the past but we start from here to find the first relevant bucket
the proposed solution is more efficient with maturity dates far in the future
> chore: NAV finds first relevant bucket with a pointer

- src/borrower/deployer.sol
- src/borrower/fabs/navfeed.creditline.sol
- src/borrower/fabs/navfeed.principal.sol
- src/borrower/fabs/pile.sol
- src/borrower/fabs/shelf.sol
- src/borrower/fabs/title.sol
- src/borrower/feed/creditline.sol
- src/borrower/feed/discounting.sol
- src/borrower/feed/navfeed.sol
- src/borrower/pile.sol
- src/borrower/shelf.sol
- src/borrower/wrappers/writeOffWrapper.sol
I started to add `NatSpec` comments for the borrower contracts.
It is a commonly used standard nowadays for Solidity.
Writing those comments is surprisingly easy together with Github Copilot. 
For me, it is also an excellent way to refresh my understanding of the codebase again.
> docs: added NatSpec comments for borrower contracts

- script/rpc-tests/rpc-tests.sol
- script/run-rpc-tests.s.sol
**Basic RPC Tests**
- remove `clerk` dependency from pool for basic rpc-test if needed
- optional removal from assessor
- optional removal from reserve
**MKR RPC Tests**
- revert immediately if MKR is not live
- for example MKR spell not executed
> rpc-tests: deactivate clerk for basic tests
